<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>isaac_3d_lidar_exploration</name>
  <version>0.1.0</version>
  <description>Portable Nav2 frontier exploration for live nvblox maps.</description>
  <maintainer email="shenfq@todo.todo">shenfq</maintainer>
  <license>Apache-2.0</license>

  <depend>action_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>nav2_bringup</depend>
  <depend>nav2_common</depend>
  <depend>nav2_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>pointcloud_to_laserscan</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>
  <depend>topic_tools</depend>
  <depend>visualization_msgs</depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
